### ISSUE TITLE
Demo only shows black screen with some white rectangles in top-left-corner

### ISSUE THREAD

**Issue by floooh** [fungos/fips-turbobadger#4]
Quick question: does the demo work for you? I'm only getting a black windows with some white rectangle in the top left corner. I tested on OSX and Windows (on Windows, only a 32-bit config currently compiles).

**Comment by fungos** [comment]
I had made a PR with thes fixes, but while it is not accepted I'm redirecting git to my fork.
The issue with win64 was a missing cast to WNDPROC.
And the issue with the blackscreen with rectangles is because the demo try to change the workdir to the same path as the executable, this breaks when because we are inside fips-deploy. So I've added a ifdef to the demo to skip this if building with fips.
Now  as it is pointing to my fork, it should work on windows, macos I'm not sure. :)

**Comment by floooh** [comment]
Works on Windows now, OSX still showing black screen, I'll see if I can come up with a PR in the evening.
